version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    ports:
      - "5054:5054/tcp"
      - "5054:5054/udp"

    networks:
      pihole_net:
        ipv4_address: 10.1.1.2

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8100:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - ServerIP=10.1.1.3
      - IPv6=false
      - TZ=Australia/Melbourne
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - '${APPS_DIRECTORY}/pihole/etc-pihole/:/etc/pihole/'
      - '${APPS_DIRECTORY}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'

    networks:
      traefik-proxy:
        ipv4_address: 192.168.200.254
      pihole_net:
        ipv4_address: 10.1.1.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOST}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.1.1.0/29