version: '3'

services:
  watchtower:
    image: my-special-tower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    networks:
      - traefik-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  traefik-proxy:
    external: true